### ISSUE TITLE
The question about the window size of the gop

### ISSUE THREAD

**Issue by qtct** [YounggjuuChoi/HiRN#1]
Hello. The window size of gop in the code is 16, which is different from 32 in the paper. In addition, can the window size of gop be set to any size as the number of input frames? Thank you for your attention.

**Comment by YounggjuuChoi** [comment]
Hello. 
The number of frames for the proposed method was set to 32 in training.
In 'options/train/HiRN/train_HiRN_REDS.yml' file, 'num_frame: 32' means the number of frames in training.
And we set the size of GOP to 16 when the number of frames >= 16.
Therefore, for the bi-directional access propagation, two propagation steps are performed as shown in 'basicsr/archs/hirn_arch.py' lines from 270 to 347.
If you want to change the size of GOP, you have to change the source code 'basicsr/archs/hirn_arch.py' lines from 180 to 189.
And if you want to change the number of frames in training, you have to change the yml file 'options/train/HiRN/train_HiRN_REDS.yml' line 21.
Thank you.

**Comment by qtct** [comment]
> Hello. The number of frames for the proposed method was set to 32 in training. In 'options/train/HiRN/train_HiRN_REDS.yml' file, 'num_frame: 32' means the number of frames in training. And we set the size of GOP to 16 when the number of frames >= 16. Therefore, for the bi-directional access propagation, two propagation steps are performed as shown in 'basicsr/archs/hirn_arch.py' lines from 270 to 347. If you want to change the size of GOP, you have to change the source code 'basicsr/archs/hirn_arch.py' lines from 180 to 189. And if you want to change the number of frames in training, you have to change the yml file 'options/train/HiRN/train_HiRN_REDS.yml' line 21. Thank you.

Thank you for your reply. I understand. Best wishes.
